# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Evently' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Evently

  target 'EventlyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EventlyUITests' do
    # Pods for testing
  end

end

plugin 'cocoapods-keys', {
    :project => "Evently",
    :target => "Evently",
    :keys => [
        "seatGeekClientID",
        "seatGeekClientSecret"
    ]
}
