source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'Evently' do
  use_frameworks!
  target 'EventlyTests' do
    inherit! :search_paths
  end
  target 'EventlyUITests' do
    # Pods for testing
  end
end

plugin 'cocoapods-keys', {
    :project => "Evently",
    :target => "Evently",
    :keys => [
        "seatGeekClientID",
        "seatGeekClientSecret"
    ]
}
